package storage

import (
	"database/sql"
	"errors"
	"os"
	"path/filepath"
	"testing"
)

// TestReleaseUpgradeFromV114 exercises the only release upgrade baseline the
// repository documents: the immediately previous release. The SQL fixture is
// a representative, schema-41 database generated by v1.14.0; it deliberately
// includes a story, session, message, save, timeline, protagonist, and NPC.
func TestReleaseUpgradeFromV114(t *testing.T) {
	path := filepath.Join(t.TempDir(), "release-v1.14.db")
	loadReleaseSQLFixture(t, path, "testdata/release/v1.14.0.sql")

	db, err := Open(path)
	if err != nil {
		t.Fatalf("upgrade v1.14.0 fixture: %v", err)
	}
	defer db.Close()

	assertSQLiteHealthy(t, db.Conn())

	var latestVersion int
	if err := db.Conn().QueryRow(`SELECT MAX(version) FROM schema_version`).Scan(&latestVersion); err != nil {
		t.Fatalf("latest schema version: %v", err)
	}
	if latestVersion != 44 {
		t.Fatalf("latest schema version=%d, want 44", latestVersion)
	}

	for _, table := range []string{
		"visual_asset_uploads",
		"translation_glossary_entries",
		"content_translations",
		"translation_jobs",
		"translation_job_items",
	} {
		var name string
		if err := db.Conn().QueryRow(`SELECT name FROM sqlite_master WHERE type='table' AND name=?`, table).Scan(&name); err != nil {
			t.Fatalf("migration table %s: %v", table, err)
		}
	}

	var storyID, activeBranchID, sessionBranchID, sessionCommitID, messageBranchID, messageCommitID, saveBranchID, saveCommitID string
	err = db.Conn().QueryRow(`
		SELECT s.id,s.active_branch_id,se.branch_id,se.source_commit_id,m.branch_id,m.source_commit_id,sv.branch_id,sv.source_commit_id
		FROM stories s
		JOIN sessions se ON se.story_id=s.id
		JOIN chat_messages m ON m.story_id=s.id
		JOIN saves sv ON sv.story_id=s.id
		WHERE s.id='release-story'`).Scan(
		&storyID, &activeBranchID, &sessionBranchID, &sessionCommitID, &messageBranchID, &messageCommitID, &saveBranchID, &saveCommitID,
	)
	if err != nil {
		t.Fatalf("load release fixture lineage: %v", err)
	}
	if storyID != "release-story" || activeBranchID == "" || sessionBranchID != activeBranchID || messageBranchID != activeBranchID || saveBranchID != activeBranchID {
		t.Fatalf("branch lineage lost: story=%q active=%q session=%q message=%q save=%q", storyID, activeBranchID, sessionBranchID, messageBranchID, saveBranchID)
	}
	for _, commitID := range []string{sessionCommitID, messageCommitID, saveCommitID} {
		var count int
		if err := db.Conn().QueryRow(`SELECT COUNT(*) FROM turn_commits WHERE id=? AND story_id=?`, commitID, storyID).Scan(&count); err != nil || count != 1 {
			t.Fatalf("lineage commit %q missing after upgrade (count=%d err=%v)", commitID, count, err)
		}
	}
}

func loadReleaseSQLFixture(t *testing.T, path, fixture string) {
	t.Helper()
	payload, err := os.ReadFile(fixture)
	if err != nil {
		t.Fatalf("read fixture %s: %v", fixture, err)
	}
	conn, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatalf("open fixture database: %v", err)
	}
	defer conn.Close()
	if _, err := conn.Exec(string(payload)); err != nil {
		t.Fatalf("load fixture %s: %v", fixture, err)
	}
}

func assertSQLiteHealthy(t *testing.T, conn *sql.DB) {
	t.Helper()
	var integrity string
	if err := conn.QueryRow(`PRAGMA integrity_check`).Scan(&integrity); err != nil {
		t.Fatalf("integrity_check: %v", err)
	}
	if integrity != "ok" {
		t.Fatalf("integrity_check=%q, want ok", integrity)
	}
	rows, err := conn.Query(`PRAGMA foreign_key_check`)
	if err != nil {
		t.Fatalf("foreign_key_check: %v", err)
	}
	defer rows.Close()
	if rows.Next() {
		var table, parent string
		var rowID sql.NullInt64
		var foreignKeyID int
		if err := rows.Scan(&table, &rowID, &parent, &foreignKeyID); err != nil {
			t.Fatalf("scan foreign_key_check: %v", err)
		}
		t.Fatalf("foreign key violation: table=%s row=%v parent=%s fk=%d", table, rowID, parent, foreignKeyID)
	}
	if err := rows.Err(); err != nil && !errors.Is(err, sql.ErrNoRows) {
		t.Fatalf("foreign_key_check rows: %v", err)
	}
}
