package engine

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"

	"github.com/crimsab/oneday/internal/storage"
)

// RelationshipAxes captures richer social state than a single disposition scalar.
type RelationshipAxes struct {
	Trust    int `json:"trust"`
	Fear     int `json:"fear"`
	Debt     int `json:"debt"`
	Respect  int `json:"respect"`
	Intimacy int `json:"intimacy"`
}

// StoryHook tracks unresolved narrative threads without turning them into rigid quests.
type StoryHook struct {
	ID          string `json:"id"`
	Kind        string `json:"kind"`
	Title       string `json:"title"`
	Detail      string `json:"detail,omitempty"`
	Status      string `json:"status,omitempty"` // active, cooling, resolved
	NPCName     string `json:"npc_name,omitempty"`
	TimerTurns  int    `json:"timer_turns,omitempty"`
	SourceTurn  int    `json:"source_turn,omitempty"`
	UpdatedTurn int    `json:"updated_turn,omitempty"`
}

// WorldReaction captures visible rumors, heat, notoriety, and delayed fallout.
type WorldReaction struct {
	ID          string `json:"id"`
	Kind        string `json:"kind"`
	Title       string `json:"title"`
	Detail      string `json:"detail,omitempty"`
	Status      string `json:"status,omitempty"` // active, cooling, resolved
	SourceTurn  int    `json:"source_turn,omitempty"`
	CreatedTurn int    `json:"created_turn,omitempty"`
}

// FrontPressure captures local pressure generated by an active faction front.
type FrontPressure struct {
	Region      string `json:"region"`
	Kind        string `json:"kind"`
	Level       int    `json:"level"`
	Detail      string `json:"detail,omitempty"`
	UpdatedTurn int    `json:"updated_turn,omitempty"`
}

// Front tracks a long-running faction agenda independently of momentary prose.
type Front struct {
	ID                 string          `json:"id"`
	Faction            string          `json:"faction"`
	Title              string          `json:"title"`
	PublicTitle        string          `json:"public_title,omitempty"`
	Stakes             string          `json:"stakes,omitempty"`
	PublicStakes       string          `json:"public_stakes,omitempty"`
	Status             string          `json:"status,omitempty"`     // active, stalled, resolved
	Visibility         string          `json:"visibility,omitempty"` // hidden, rumored, known
	Segments           int             `json:"segments,omitempty"`
	Progress           int             `json:"progress,omitempty"`
	LastAdvancedTurn   int             `json:"last_advanced_turn,omitempty"`
	NextEscalationTurn int             `json:"next_escalation_turn,omitempty"`
	Resolution         string          `json:"resolution,omitempty"`
	Pressures          []FrontPressure `json:"pressures,omitempty"`
}

// TurnDeltaItem is a single player-facing consequence line.
type TurnDeltaItem struct {
	Kind   string `json:"kind,omitempty"`
	Label  string `json:"label"`
	Detail string `json:"detail,omitempty"`
}

// TurnDelta is the structured "What changed this turn?" payload.
type TurnDelta struct {
	Items []TurnDeltaItem `json:"items,omitempty"`
}

func clampRelationshipValue(v int) int {
	if v > 100 {
		return 100
	}
	if v < -100 {
		return -100
	}
	return v
}

func loadRelationshipAxes(npc *storage.NPC) RelationshipAxes {
	if npc == nil || strings.TrimSpace(npc.RelationshipJSON) == "" || strings.TrimSpace(npc.RelationshipJSON) == "{}" {
		return RelationshipAxes{}
	}
	var axes RelationshipAxes
	if err := json.Unmarshal([]byte(npc.RelationshipJSON), &axes); err != nil {
		return RelationshipAxes{}
	}
	axes.Trust = clampRelationshipValue(axes.Trust)
	axes.Fear = clampRelationshipValue(axes.Fear)
	axes.Debt = clampRelationshipValue(axes.Debt)
	axes.Respect = clampRelationshipValue(axes.Respect)
	axes.Intimacy = clampRelationshipValue(axes.Intimacy)
	return axes
}

func storeRelationshipAxes(npc *storage.NPC, axes RelationshipAxes) {
	if npc == nil {
		return
	}
	axes.Trust = clampRelationshipValue(axes.Trust)
	axes.Fear = clampRelationshipValue(axes.Fear)
	axes.Debt = clampRelationshipValue(axes.Debt)
	axes.Respect = clampRelationshipValue(axes.Respect)
	axes.Intimacy = clampRelationshipValue(axes.Intimacy)
	if payload, err := json.Marshal(axes); err == nil {
		npc.RelationshipJSON = string(payload)
	}
}

func loadStoryHooks(world *storage.WorldState) []StoryHook {
	if world == nil || strings.TrimSpace(world.StoryHooksJSON) == "" || strings.TrimSpace(world.StoryHooksJSON) == "[]" {
		return nil
	}
	var hooks []StoryHook
	if err := json.Unmarshal([]byte(world.StoryHooksJSON), &hooks); err != nil {
		return nil
	}
	return normalizeStoryHooks(hooks)
}

func storeStoryHooks(world *storage.WorldState, hooks []StoryHook) {
	if world == nil {
		return
	}
	if payload, err := json.Marshal(normalizeStoryHooks(hooks)); err == nil {
		world.StoryHooksJSON = string(payload)
	}
}

func loadWorldReactions(world *storage.WorldState) []WorldReaction {
	if world == nil || strings.TrimSpace(world.WorldReactionsJSON) == "" || strings.TrimSpace(world.WorldReactionsJSON) == "[]" {
		return nil
	}
	var reactions []WorldReaction
	if err := json.Unmarshal([]byte(world.WorldReactionsJSON), &reactions); err != nil {
		return nil
	}
	return normalizeWorldReactions(reactions)
}

func storeWorldReactions(world *storage.WorldState, reactions []WorldReaction) {
	if world == nil {
		return
	}
	if payload, err := json.Marshal(normalizeWorldReactions(reactions)); err == nil {
		world.WorldReactionsJSON = string(payload)
	}
}

func loadFronts(world *storage.WorldState) []Front {
	if world == nil || strings.TrimSpace(world.FrontsJSON) == "" || strings.TrimSpace(world.FrontsJSON) == "[]" {
		return nil
	}
	var fronts []Front
	if err := json.Unmarshal([]byte(world.FrontsJSON), &fronts); err != nil {
		return nil
	}
	return normalizeFronts(fronts)
}

func storeFronts(world *storage.WorldState, fronts []Front) {
	if world == nil {
		return
	}
	if payload, err := json.Marshal(normalizeFronts(fronts)); err == nil {
		world.FrontsJSON = string(payload)
	}
}

func normalizeStoryHooks(hooks []StoryHook) []StoryHook {
	if len(hooks) == 0 {
		return nil
	}
	out := make([]StoryHook, 0, len(hooks))
	seen := map[string]bool{}
	for _, hook := range hooks {
		hook.Title = strings.TrimSpace(hook.Title)
		hook.Detail = strings.TrimSpace(hook.Detail)
		hook.Kind = strings.TrimSpace(hook.Kind)
		hook.NPCName = strings.TrimSpace(hook.NPCName)
		hook.Status = strings.TrimSpace(hook.Status)
		if hook.ID == "" {
			hook.ID = uuid.NewString()
		}
		if hook.Status == "" {
			hook.Status = "active"
		}
		if hook.Title == "" {
			continue
		}
		key := strings.ToLower(hook.ID + "|" + hook.Title + "|" + hook.Status)
		if seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, hook)
	}
	return out
}

func normalizeWorldReactions(reactions []WorldReaction) []WorldReaction {
	if len(reactions) == 0 {
		return nil
	}
	out := make([]WorldReaction, 0, len(reactions))
	seen := map[string]bool{}
	for _, reaction := range reactions {
		reaction.Kind = strings.TrimSpace(reaction.Kind)
		reaction.Title = strings.TrimSpace(reaction.Title)
		reaction.Detail = strings.TrimSpace(reaction.Detail)
		reaction.Status = strings.TrimSpace(reaction.Status)
		if reaction.ID == "" {
			reaction.ID = uuid.NewString()
		}
		if reaction.Status == "" {
			reaction.Status = "active"
		}
		if reaction.Title == "" {
			continue
		}
		key := strings.ToLower(reaction.ID + "|" + reaction.Title + "|" + reaction.Status)
		if seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, reaction)
	}
	return out
}

func normalizeFronts(fronts []Front) []Front {
	if len(fronts) == 0 {
		return nil
	}
	out := make([]Front, 0, len(fronts))
	seen := map[string]bool{}
	for _, front := range fronts {
		front.ID = strings.TrimSpace(front.ID)
		front.Faction = strings.TrimSpace(front.Faction)
		front.Title = strings.TrimSpace(front.Title)
		front.PublicTitle = strings.TrimSpace(front.PublicTitle)
		front.Stakes = strings.TrimSpace(front.Stakes)
		front.PublicStakes = strings.TrimSpace(front.PublicStakes)
		front.Status = strings.TrimSpace(front.Status)
		front.Visibility = strings.TrimSpace(front.Visibility)
		front.Resolution = strings.TrimSpace(front.Resolution)
		if front.ID == "" {
			front.ID = uuid.NewString()
		}
		if front.Status == "" {
			front.Status = "active"
		}
		switch strings.ToLower(front.Visibility) {
		case "", "hidden":
			front.Visibility = "hidden"
		case "rumored", "known":
			front.Visibility = strings.ToLower(front.Visibility)
		default:
			front.Visibility = "hidden"
		}
		if front.Segments <= 0 {
			front.Segments = 4
		}
		if front.Progress < 0 {
			front.Progress = 0
		}
		if front.Progress > front.Segments {
			front.Progress = front.Segments
		}
		front.Pressures = normalizeFrontPressures(front.Pressures)
		if front.Title == "" {
			continue
		}
		key := strings.ToLower(front.ID + "|" + front.Title + "|" + front.Faction)
		if seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, front)
	}
	return out
}

func normalizeFrontPressures(pressures []FrontPressure) []FrontPressure {
	if len(pressures) == 0 {
		return nil
	}
	out := make([]FrontPressure, 0, len(pressures))
	seen := map[string]bool{}
	for _, pressure := range pressures {
		pressure.Region = strings.TrimSpace(pressure.Region)
		pressure.Kind = strings.TrimSpace(pressure.Kind)
		pressure.Detail = strings.TrimSpace(pressure.Detail)
		if pressure.Region == "" || pressure.Kind == "" {
			continue
		}
		if pressure.Level < 0 {
			pressure.Level = 0
		}
		if pressure.Level > 100 {
			pressure.Level = 100
		}
		key := strings.ToLower(pressure.Region + "|" + pressure.Kind)
		if seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, pressure)
	}
	return out
}

func knownFronts(fronts []Front) []Front {
	if len(fronts) == 0 {
		return nil
	}
	var out []Front
	for _, front := range normalizeFronts(fronts) {
		if front.Visibility == "hidden" {
			continue
		}
		out = append(out, front)
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

func frontDisplayTitle(front Front) string {
	if title := strings.TrimSpace(front.PublicTitle); title != "" {
		return title
	}
	return strings.TrimSpace(front.Title)
}

func frontDisplayStakes(front Front) string {
	switch strings.ToLower(strings.TrimSpace(front.Visibility)) {
	case "known":
		if stakes := strings.TrimSpace(front.Stakes); stakes != "" {
			return stakes
		}
	case "rumored":
		if stakes := strings.TrimSpace(front.PublicStakes); stakes != "" {
			return stakes
		}
	}
	if stakes := strings.TrimSpace(front.PublicStakes); stakes != "" {
		return stakes
	}
	return ""
}

func frontPressureSeverity(level int) string {
	switch {
	case level >= 75:
		return "critical"
	case level >= 50:
		return "high"
	case level >= 25:
		return "rising"
	default:
		return "low"
	}
}

func frontPressureEffects(pressure FrontPressure) []string {
	level := pressure.Level
	switch strings.ToLower(strings.TrimSpace(pressure.Kind)) {
	case "suspicion", "heat", "notoriety":
		switch {
		case level >= 75:
			return []string{"patrols tighten", "outsiders get stopped and priced harder"}
		case level >= 50:
			return []string{"guards question strangers", "locals stop volunteering help"}
		case level >= 25:
			return []string{"rumors spread", "guards ask sharper questions"}
		default:
			return []string{"a few eyes linger on strangers"}
		}
	case "hostility", "violence":
		switch {
		case level >= 75:
			return []string{"ambushes become likely", "safe routes start closing"}
		case level >= 50:
			return []string{"threats turn open", "escorts and bribes get pricier"}
		case level >= 25:
			return []string{"tempers rise", "rough crowds gather faster"}
		default:
			return []string{"tension keeps building"}
		}
	case "fear":
		switch {
		case level >= 75:
			return []string{"shops shutter early", "witnesses refuse to talk"}
		case level >= 50:
			return []string{"doors stay barred", "people hide useful information"}
		case level >= 25:
			return []string{"locals go quiet", "crowds thin out sooner"}
		default:
			return []string{"nerves are starting to show"}
		}
	case "influence", "control":
		switch {
		case level >= 75:
			return []string{"permits and gates are controlled", "favored allies move freely"}
		case level >= 50:
			return []string{"inspectors and enforcers show up more", "access starts depending on favors"}
		case level >= 25:
			return []string{"the faction's presence is obvious", "small decisions begin tilting their way"}
		default:
			return []string{"their pull is starting to register"}
		}
	case "scarcity":
		switch {
		case level >= 75:
			return []string{"basic supplies spike in price", "desperate deals become common"}
		case level >= 50:
			return []string{"merchants hold stock back", "repair and food costs climb"}
		case level >= 25:
			return []string{"queues get longer", "haggling turns harsher"}
		default:
			return []string{"small shortages begin to bite"}
		}
	default:
		switch {
		case level >= 75:
			return []string{"the area bends around this pressure", "ordinary routines start failing"}
		case level >= 50:
			return []string{"daily routines become harder", "people adapt defensively"}
		case level >= 25:
			return []string{"the mood of the area shifts", "small obstacles accumulate"}
		default:
			return []string{"the region is starting to feel it"}
		}
	}
}

func formatFrontPressureDisplay(pressure FrontPressure) string {
	line := fmt.Sprintf("%s [%s %d %s]", pressure.Region, pressure.Kind, pressure.Level, frontPressureSeverity(pressure.Level))
	effects := frontPressureEffects(pressure)
	if len(effects) > 0 {
		line += " - " + strings.Join(effects, "; ")
	}
	if detail := strings.TrimSpace(pressure.Detail); detail != "" {
		line += " | " + detail
	}
	return line
}

func formatKnownFrontSummary(front Front) string {
	parts := []string{frontDisplayTitle(front)}
	if strings.EqualFold(front.Visibility, "known") && strings.TrimSpace(front.Faction) != "" {
		parts = append(parts, "{"+strings.TrimSpace(front.Faction)+"}")
	}
	if front.Segments > 0 {
		parts = append(parts, fmt.Sprintf("%d/%d", front.Progress, front.Segments))
	}
	if status := strings.TrimSpace(front.Status); status != "" && !strings.EqualFold(status, "active") {
		parts = append(parts, "["+status+"]")
	}

	line := strings.Join(parts, " ")
	pressureParts := make([]string, 0, len(front.Pressures))
	for _, pressure := range normalizeFrontPressures(front.Pressures) {
		pressureParts = append(pressureParts, formatFrontPressureDisplay(pressure))
	}
	if len(pressureParts) > 0 {
		line += " | pressure: " + strings.Join(pressureParts, " || ")
	}
	return line
}

func frontHookStatus(front Front) string {
	switch strings.ToLower(strings.TrimSpace(front.Status)) {
	case "resolved":
		return "resolved"
	case "stalled":
		return "cooling"
	default:
		return "active"
	}
}

func frontContinuityHook(front Front, currentTurn int) StoryHook {
	title := frontDisplayTitle(front)
	if title == "" {
		return StoryHook{}
	}

	detail := frontDisplayStakes(front)
	if strings.EqualFold(front.Status, "resolved") && strings.TrimSpace(front.Resolution) != "" {
		detail = strings.TrimSpace(front.Resolution)
	}
	if detail == "" {
		pressures := normalizeFrontPressures(front.Pressures)
		if len(pressures) > 0 {
			detail = formatFrontPressureDisplay(pressures[0])
		}
	}

	timerTurns := 0
	if front.NextEscalationTurn > currentTurn {
		timerTurns = front.NextEscalationTurn - currentTurn
	}

	sourceTurn := front.LastAdvancedTurn
	if sourceTurn <= 0 {
		sourceTurn = currentTurn
	}

	return StoryHook{
		ID:          "front-hook:" + front.ID,
		Kind:        "front",
		Title:       title,
		Detail:      detail,
		Status:      frontHookStatus(front),
		TimerTurns:  timerTurns,
		SourceTurn:  sourceTurn,
		UpdatedTurn: currentTurn,
	}
}

func frontPressureReactionTitle(front Front, pressure FrontPressure) string {
	base := frontDisplayTitle(front)
	region := strings.TrimSpace(pressure.Region)
	switch strings.ToLower(strings.TrimSpace(pressure.Kind)) {
	case "suspicion", "heat", "notoriety":
		return region + " grows watchful around " + base
	case "hostility", "violence":
		return region + " turns openly dangerous around " + base
	case "fear":
		return region + " starts shutting itself in"
	case "influence", "control":
		return base + " tightens its grip on " + region
	case "scarcity":
		return region + " starts feeling the squeeze"
	default:
		return region + " shifts under " + base
	}
}

func slugKey(value string) string {
	value = strings.TrimSpace(strings.ToLower(value))
	if value == "" {
		return "item"
	}

	var sb strings.Builder
	lastDash := false
	for _, r := range value {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			sb.WriteRune(r)
			lastDash = false
		default:
			if sb.Len() == 0 || lastDash {
				continue
			}
			sb.WriteByte('-')
			lastDash = true
		}
	}
	out := strings.Trim(sb.String(), "-")
	if out == "" {
		return "item"
	}
	return out
}

func frontPressureReaction(front Front, pressure FrontPressure, currentTurn int) WorldReaction {
	if strings.TrimSpace(pressure.Region) == "" || strings.TrimSpace(pressure.Kind) == "" {
		return WorldReaction{}
	}

	title := strings.TrimSpace(frontPressureReactionTitle(front, pressure))
	if title == "" {
		return WorldReaction{}
	}

	createdTurn := pressure.UpdatedTurn
	if createdTurn <= 0 {
		createdTurn = currentTurn
	}

	status := "active"
	if strings.EqualFold(front.Status, "resolved") {
		status = "resolved"
	}

	return WorldReaction{
		ID:          "front-pressure:" + front.ID + ":" + slugKey(pressure.Region) + ":" + slugKey(pressure.Kind),
		Kind:        "front_pressure",
		Title:       title,
		Detail:      frontDisplayTitle(front) + " - " + formatFrontPressureDisplay(pressure),
		Status:      status,
		SourceTurn:  pressure.UpdatedTurn,
		CreatedTurn: createdTurn,
	}
}

func upsertFrontPressure(front *Front, pressure FrontPressure) {
	if front == nil {
		return
	}
	pressures := normalizeFrontPressures(front.Pressures)
	replaced := false
	for i := range pressures {
		if strings.EqualFold(pressures[i].Region, pressure.Region) && strings.EqualFold(pressures[i].Kind, pressure.Kind) {
			pressures[i] = pressure
			replaced = true
			break
		}
	}
	if !replaced {
		pressures = append(pressures, pressure)
	}
	front.Pressures = normalizeFrontPressures(pressures)
}

func syncKnownFrontContinuity(world *storage.WorldState, currentTurn int) {
	if world == nil {
		return
	}

	hooks := loadStoryHooks(world)
	reactions := loadWorldReactions(world)
	activeHooks := map[string]StoryHook{}
	activeReactions := map[string]WorldReaction{}

	for _, front := range knownFronts(loadFronts(world)) {
		hook := frontContinuityHook(front, currentTurn)
		if hook.ID != "" {
			activeHooks[hook.ID] = hook
		}
		for _, pressure := range normalizeFrontPressures(front.Pressures) {
			reaction := frontPressureReaction(front, pressure, currentTurn)
			if reaction.ID != "" {
				activeReactions[reaction.ID] = reaction
			}
		}
	}

	for i := range hooks {
		if !strings.HasPrefix(hooks[i].ID, "front-hook:") {
			continue
		}
		replacement, ok := activeHooks[hooks[i].ID]
		if !ok {
			hooks[i].Status = "resolved"
			hooks[i].TimerTurns = 0
			hooks[i].UpdatedTurn = currentTurn
			continue
		}
		if hooks[i].SourceTurn > 0 {
			replacement.SourceTurn = hooks[i].SourceTurn
		}
		hooks[i] = replacement
		delete(activeHooks, replacement.ID)
	}
	for _, hook := range activeHooks {
		hooks = append(hooks, hook)
	}

	for i := range reactions {
		if !strings.HasPrefix(reactions[i].ID, "front-pressure:") {
			continue
		}
		replacement, ok := activeReactions[reactions[i].ID]
		if !ok {
			reactions[i].Status = "resolved"
			continue
		}
		if reactions[i].CreatedTurn > 0 {
			replacement.CreatedTurn = reactions[i].CreatedTurn
		}
		reactions[i] = replacement
		delete(activeReactions, replacement.ID)
	}
	for _, reaction := range activeReactions {
		reactions = append(reactions, reaction)
	}

	storeStoryHooks(world, hooks)
	storeWorldReactions(world, reactions)
}

func applyFailForwardToFronts(world *storage.WorldState, val interface{}, currentTurn int) []StateChange {
	if world == nil {
		return nil
	}

	fronts := loadFronts(world)
	if len(fronts) == 0 {
		return nil
	}

	var applied []StateChange
	updated := false
	for _, failMap := range toObjectMaps(val) {
		title := strings.TrimSpace(stringValue(failMap["front_title"]))
		if title == "" {
			title = strings.TrimSpace(stringValue(failMap["front"]))
		}
		idx := findFrontIndex(fronts, strings.TrimSpace(stringValue(failMap["front_id"])), title)
		if idx < 0 {
			continue
		}

		advance := int(toFloat(failMap["front_advance"]))
		if advance <= 0 {
			advance = 1
		}
		fronts[idx].Progress += advance
		if fronts[idx].Progress > fronts[idx].Segments {
			fronts[idx].Progress = fronts[idx].Segments
		}
		fronts[idx].LastAdvancedTurn = currentTurn
		if status := strings.TrimSpace(stringValue(failMap["front_status"])); status != "" {
			fronts[idx].Status = status
		}
		applied = append(applied, StateChange{
			Target:      "world",
			Field:       fmt.Sprintf("front.%s", frontDisplayTitle(fronts[idx])),
			New:         fronts[idx].Progress,
			Description: fmt.Sprintf("Front advances: %s", frontDisplayTitle(fronts[idx])),
		})

		region := strings.TrimSpace(stringValue(failMap["pressure_region"]))
		kind := strings.TrimSpace(stringValue(failMap["pressure_kind"]))
		if region != "" && kind != "" {
			level := int(toFloat(failMap["pressure_value"]))
			if changeVal, ok := failMap["pressure_change"]; ok {
				level = int(toFloat(changeVal))
				for i := range fronts[idx].Pressures {
					if strings.EqualFold(fronts[idx].Pressures[i].Region, region) && strings.EqualFold(fronts[idx].Pressures[i].Kind, kind) {
						level = fronts[idx].Pressures[i].Level + int(toFloat(changeVal))
						break
					}
				}
			} else if level <= 0 {
				level = 15
			}
			upsertFrontPressure(&fronts[idx], FrontPressure{
				Region:      region,
				Kind:        kind,
				Level:       level,
				Detail:      strings.TrimSpace(stringValue(failMap["pressure_detail"])),
				UpdatedTurn: currentTurn,
			})
			applied = append(applied, StateChange{
				Target:      "world",
				Field:       fmt.Sprintf("front_pressure.%s.%s", region, kind),
				New:         level,
				Description: fmt.Sprintf("Pressure rises in %s", region),
			})
		}
		updated = true
	}

	if updated {
		storeFronts(world, fronts)
		syncKnownFrontContinuity(world, currentTurn)
	}

	return applied
}

func findFrontIndex(fronts []Front, id, title string) int {
	id = strings.TrimSpace(id)
	title = strings.TrimSpace(title)
	for i, front := range fronts {
		if id != "" && strings.EqualFold(front.ID, id) {
			return i
		}
		if title != "" && strings.EqualFold(front.Title, title) {
			return i
		}
		if title != "" && front.PublicTitle != "" && strings.EqualFold(front.PublicTitle, title) {
			return i
		}
	}
	return -1
}

func activeStoryHooks(hooks []StoryHook) []StoryHook {
	if len(hooks) == 0 {
		return nil
	}
	active := make([]StoryHook, 0, len(hooks))
	for _, hook := range normalizeStoryHooks(hooks) {
		if strings.EqualFold(hook.Status, "resolved") {
			continue
		}
		active = append(active, hook)
	}
	if len(active) == 0 {
		return nil
	}
	return active
}

func visibleWorldReactions(reactions []WorldReaction) []WorldReaction {
	if len(reactions) == 0 {
		return nil
	}
	visible := make([]WorldReaction, 0, len(reactions))
	for _, reaction := range normalizeWorldReactions(reactions) {
		if strings.EqualFold(reaction.Status, "resolved") {
			continue
		}
		visible = append(visible, reaction)
	}
	if len(visible) == 0 {
		return nil
	}
	return visible
}

func mergeTurnDelta(engineDelta, aiDelta *TurnDelta) *TurnDelta {
	switch {
	case engineDelta == nil && aiDelta == nil:
		return nil
	case engineDelta == nil:
		return normalizeTurnDelta(aiDelta)
	case aiDelta == nil:
		return normalizeTurnDelta(engineDelta)
	}

	merged := &TurnDelta{
		Items: append([]TurnDeltaItem{}, engineDelta.Items...),
	}
	merged.Items = append(merged.Items, aiDelta.Items...)
	return normalizeTurnDelta(merged)
}

func normalizeTurnDelta(delta *TurnDelta) *TurnDelta {
	if delta == nil || len(delta.Items) == 0 {
		return nil
	}
	out := &TurnDelta{Items: make([]TurnDeltaItem, 0, len(delta.Items))}
	seen := map[string]bool{}
	for _, item := range delta.Items {
		item.Kind = strings.TrimSpace(item.Kind)
		item.Label = strings.TrimSpace(item.Label)
		item.Detail = strings.TrimSpace(item.Detail)
		if item.Label == "" && item.Detail == "" {
			continue
		}
		key := strings.ToLower(item.Kind + "|" + item.Label + "|" + item.Detail)
		if seen[key] {
			continue
		}
		seen[key] = true
		out.Items = append(out.Items, item)
	}
	if len(out.Items) == 0 {
		return nil
	}
	return out
}

func buildTurnDelta(changes []StateChange) *TurnDelta {
	if len(changes) == 0 {
		return nil
	}
	items := make([]TurnDeltaItem, 0, len(changes))
	for _, change := range changes {
		label := strings.TrimSpace(change.Description)
		kind := "world"
		switch {
		case strings.HasPrefix(change.Field, "vitals.") || strings.HasPrefix(change.Field, "attributes.") || strings.HasPrefix(change.Field, "secondary.") || change.Field == "currency":
			kind = "stat"
		case change.Field == "inventory":
			if change.Old == nil && change.New != nil {
				kind = "inventory_gain"
			} else if change.Old != nil && change.New == nil {
				kind = "inventory_loss"
			} else {
				kind = "inventory"
			}
		case strings.HasPrefix(change.Field, "npc.") || strings.HasPrefix(change.Field, "relationship."):
			kind = "relationship"
		case strings.HasPrefix(change.Field, "hook."):
			kind = "hook"
		case strings.HasPrefix(change.Field, "reaction."):
			kind = "reaction"
		case strings.Contains(change.Field, "setting_") || strings.HasPrefix(change.Field, "world_"):
			kind = "lore"
		case change.Field == "location":
			kind = "world"
		}

		if label == "" {
			if change.Field == "location" {
				label = "Location changed"
			} else {
				label = strings.ReplaceAll(change.Field, ".", " ")
			}
		}

		detail := ""
		if kind == "stat" && change.Old != nil && change.New != nil {
			detail = strings.TrimSpace(formatValueTransition(change.Old, change.New))
		}
		items = append(items, TurnDeltaItem{
			Kind:   kind,
			Label:  label,
			Detail: detail,
		})
	}
	return normalizeTurnDelta(&TurnDelta{Items: items})
}

func formatValueTransition(oldValue, newValue interface{}) string {
	oldText := strings.TrimSpace(toDisplayString(oldValue))
	newText := strings.TrimSpace(toDisplayString(newValue))
	switch {
	case oldText == "" && newText == "":
		return ""
	case oldText == "":
		return newText
	case newText == "":
		return oldText
	default:
		return oldText + " -> " + newText
	}
}

func toDisplayString(value interface{}) string {
	switch v := value.(type) {
	case nil:
		return ""
	case string:
		return v
	case int:
		return jsonNumberString(v)
	case int64:
		return jsonNumberString(v)
	case float64:
		return jsonNumberString(v)
	case time.Time:
		return v.Format(time.RFC3339)
	default:
		payload, err := json.Marshal(v)
		if err != nil {
			return ""
		}
		return string(payload)
	}
}

func jsonNumberString[T ~int | ~int64 | ~float64](value T) string {
	payload, err := json.Marshal(value)
	if err != nil {
		return ""
	}
	return string(payload)
}

// FormatStoryTrackerView renders the persistent hooks, discovered fronts, and world-reaction feed for overlays.
func FormatStoryTrackerView(world *storage.WorldState) string {
	if world == nil {
		return "No tracker data available."
	}

	hooks := activeStoryHooks(loadStoryHooks(world))
	fronts := knownFronts(loadFronts(world))
	reactions := visibleWorldReactions(loadWorldReactions(world))
	if len(hooks) == 0 && len(fronts) == 0 && len(reactions) == 0 {
		return "No open hooks, discovered fronts, or active world reactions yet."
	}

	var sb strings.Builder
	if len(hooks) > 0 {
		sb.WriteString("## Open Hooks\n")
		for _, hook := range hooks {
			sb.WriteString("- " + hook.Title)
			if hook.Kind != "" {
				sb.WriteString(fmt.Sprintf(" [%s]", hook.Kind))
			}
			if hook.NPCName != "" {
				sb.WriteString(fmt.Sprintf(" {%s}", hook.NPCName))
			}
			if hook.TimerTurns > 0 {
				sb.WriteString(fmt.Sprintf(" (timer %d)", hook.TimerTurns))
			}
			sb.WriteString("\n")
			if hook.Detail != "" {
				sb.WriteString("  " + hook.Detail + "\n")
			}
		}
	}

	if len(fronts) > 0 {
		if sb.Len() > 0 {
			sb.WriteString("\n")
		}
		sb.WriteString("## Open Fronts\n")
		for _, front := range fronts {
			sb.WriteString("- " + frontDisplayTitle(front))
			if strings.EqualFold(front.Visibility, "known") && front.Faction != "" {
				sb.WriteString(fmt.Sprintf(" {%s}", front.Faction))
			}
			if front.Segments > 0 {
				sb.WriteString(fmt.Sprintf(" (%d/%d)", front.Progress, front.Segments))
			}
			if status := strings.TrimSpace(front.Status); status != "" && !strings.EqualFold(status, "active") {
				sb.WriteString(fmt.Sprintf(" [%s]", status))
			}
			sb.WriteString("\n")
			if stakes := frontDisplayStakes(front); stakes != "" {
				sb.WriteString("  Stakes: " + stakes + "\n")
			}
			for _, pressure := range normalizeFrontPressures(front.Pressures) {
				sb.WriteString("  Pressure: " + formatFrontPressureDisplay(pressure) + "\n")
			}
			if resolution := strings.TrimSpace(front.Resolution); resolution != "" && strings.EqualFold(front.Status, "resolved") {
				sb.WriteString("  Outcome: " + resolution + "\n")
			}
		}
	}

	if len(reactions) > 0 {
		if sb.Len() > 0 {
			sb.WriteString("\n")
		}
		sb.WriteString("## World Reaction Feed\n")
		for _, reaction := range reactions {
			sb.WriteString("- " + reaction.Title)
			if reaction.Kind != "" {
				sb.WriteString(fmt.Sprintf(" [%s]", reaction.Kind))
			}
			sb.WriteString("\n")
			if reaction.Detail != "" {
				sb.WriteString("  " + reaction.Detail + "\n")
			}
		}
	}

	return strings.TrimSpace(sb.String())
}
